export const ACCOUNTANT_MANUAL_SOCKET_INIT_DATA                 = 'ACCOUNTANT_MANUAL_SOCKET_INIT_DATA'
export const ACCOUNTANT_MANUAL_SOCKET_GET_BANKER_DATA           = 'ACCOUNTANT_MANUAL_SOCKET_GET_BANKER_DATA'
export const ACCOUNTANT_MANUAL_SOCKET_SCAN_FORM_BANKER          = 'ACCOUNTANT_MANUAL_SOCKET_SCAN_FORM_BANKER'
export const ACCOUNTANT_MANUAL_SOCKET_SUBMIT_FORM_BANKER        = 'ACCOUNTANT_MANUAL_SOCKET_SUBMIT_FORM_BANKER'
