export const GET_MEMBER_SUB                 = 'GET_MEMBER_SUB';
export const GET_SUFFIXES_MEMBER            = 'GET_SUFFIXES_MEMBER';
export const DEL_MEMBER_SUB                 = 'DEL_MEMBER_SUB';
export const CREATE_MEMBER_SUB              = 'CREATE_MEMBER_SUB';
export const RESET_FORM_SAVE_ACCOUNT_SUB    = 'RESET_FORM_SAVE_ACCOUNT_SUB';
export const MEMBER_SUB_TOGGLE_MODAL_FORM   = 'MEMBER_SUB_TOGGLE_MODAL_DELETE_FORMULA';
