export const AUTH_LOGIN_SUCCESS         = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL            = 'AUTH_LOGIN_FAIL';

export const AUTH_GET_SECURE_SUCCESS    = 'AUTH_GET_SECURE_SUCCESS';
export const AUTH_GET_SECURE_FAIL       = 'AUTH_GET_SECURE_FAIL';

export const AUTH_CHECK_SECURE_SUCCESS    = 'AUTH_CHECK_SECURE_SUCCESS';
export const AUTH_CHECK_SECURE_FAIL       = 'AUTH_CHECK_SECURE_FAIL';