/*========GET ACCOUNTANT CONFIG========*/
export const GET_ACCOUNTANT_CONFIG_SUCCESS   = 'GET_ACCOUNTANT_CONFIG_SUCCESS';
export const GET_ACCOUNTANT_CONFIG_FAIL      = 'GET_ACCOUNTANT_CONFIG_FAIL';

/*========GET COMPANY CONFIG========*/
export const GET_COMPANY_CONFIG_SUCCESS   = 'GET_COMPANY_CONFIG_SUCCESS';
export const GET_COMPANY_CONFIG_FAIL      = 'GET_COMPANY_CONFIG_FAIL';

/*========GET CURRENCY CONFIG========*/
export const GET_CURRENCY_CONFIG_SUCCESS   = 'GET_CURRENCY_CONFIG_SUCCESS';
export const GET_CURRENCY_CONFIG_FAIL      = 'GET_CURRENCY_CONFIG_FAIL';

/*========SAVE ACCOUNTANT CONFIG========*/
export const SAVE_ACCOUNTANT_CONFIG_SUCCESS   = 'SAVE_ACCOUNTANT_CONFIG_SUCCESS';
export const SAVE_ACCOUNTANT_CONFIG_FAIL      = 'SAVE_ACCOUNTANT_CONFIG_FAIL';

/*========GET COMPANY CONFIG========*/
export const SAVE_COMPANY_CONFIG_SUCCESS   = 'SAVE_COMPANY_CONFIG_SUCCESS';
export const SAVE_COMPANY_CONFIG_FAIL      = 'SAVE_COMPANY_CONFIG_FAIL';
export const RESET_FORM_SAVE_RESPONSE_COMPANY_CONFIG = 'RESET_FORM_SAVE_RESPONSE_COMPANY_CONFIG'

/*========GET CURRENCY CONFIG========*/
export const SAVE_CURRENCY_CONFIG_SUCCESS   = 'SAVE_CURRENCY_CONFIG_SUCCESS';
export const SAVE_CURRENCY_CONFIG_FAIL      = 'SAVE_CURRENCY_CONFIG_FAIL';

/*========GET INIT CURRENCY========*/
export const GET_INIT_CURRENCY_SUCCESS   = 'GET_INIT_CURRENCY_SUCCESS';
export const SAVE_INIT_CURRENCY_FAIL      = 'SAVE_INIT_CURRENCY_FAIL';

/*========SAVE CURRENCY CUSTOM FILTER CONFIG========*/
export const SAVE_CURRENCY_CUSTOM_FILTER_SUCCESS   = 'SAVE_CURRENCY_CUSTOM_FILTER_SUCCESS';
export const SAVE_CURRENCY_CUSTOM_FILTER_FAIL      = 'SAVE_CURRENCY_CUSTOM_FILTER_FAIL';

